<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8" />
    <!-- 添加meta标签指定字符编码为UTF-8 -->
    <title>YYT-deepseek</title>
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <meta
      content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0"
      name="viewport"
    />
    <style>
      body,
      html {
        width: 100%;
        height: 100%;
        overflow-x: hidden;
        overflow-y: hidden;
      }

      * {
        margin: 0;
        padding: 0;
      }
    </style>
  </head>
  <body>
    <iframe
      src="https://share.fastgpt.in/chat/share?shareId=njtiutvojbsgo18xkw4yubyi"
      style="width: 100%; height: 100%"
      frameborder="0"
      allow="*"
    />
  </body>
</html>
